### ISSUE TITLE
Update reboot handler to wait

### ISSUE THREAD

**Issue by shaunsund** [bluepantsdev/collection-raspberrypi#1]
for system to come back

```
- name: Reboot system
  ansible.builtin.reboot:
    reboot_timeout: 300
  async: 1
  poll: 0
  ignore_errors: true
  tags:
    - always
```
